
services:
  backend:
    build:
      context: ./backend
    container_name: balabolka-backend
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1      
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: always

  db:
    image: postgres:16
    container_name: balabolka-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  frontend:
    image: nginx:1.25
    container_name: balabolka-frontend
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
